### ISSUE TITLE
Colon in event name causes issues with react 

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [planetlabs/maps#533]
Event names with colons cause issues with react. Example:

```tsx
<View onChange:center={something}/>
```

The colon character in the prop causes issues with react. With Babel this can be solved by having a `.babelrc` file like this:

```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": { "throwIfNamespace": false }
      }
    ]
  ],
  "plugins": []
}
```

But with other packages (e.g. SWC / Turbopack, etc.) this is causing issues and blocking from using this.

A solution could be to name `onChange:center` `onChange_center` in react prop for example.

**Comment by vincent-lecrubier-skydio** [comment]
Fix proposed in https://github.com/planetlabs/maps/pull/534

**Comment by tschaub** [comment]
I've added a test that demonstrates `onChange:center` style props working: https://github.com/planetlabs/maps/blob/861346b701311cc736f5045e2fcc0fd168fee32f/tests/lib/View.test.jsx#L50-L75

And I can confirm that these `onChange:prop` style listeners are working without additional configuration in Vite-based apps.

I understand that there might be bundlers where this isn't properly handled.  I'll add some thoughts on #534 related to the proposed change.
